FROM node:latest

RUN mkdir /app

WORKDIR /app

ENV TELEGRAM_BOTTOKEN=""
ENV BOT_PASSWORD=""
ENV BOT_OWNER=0
ENV RADARR_HOST=""
ENV RADARR_APIKEY=""
ENV RADARR_PORT=0
ENV RADARR_URLBASE="/"
ENV RADARR_SSL=false
ENV RADARR_USERNAME="" 
ENV RADARR_PASSWORD=""
ENV DEFAULTS_ROOT_FOLDER="/"
ENV DEFAULTS_PROFILE_ID=0
ENV DEFAULTS_MONITOR=true

COPY package*.json ./
RUN npm install

COPY . ./

CMD ["npm", "start"]
